<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ciudades')
            ->insert([
            ['id'=>1,'descripcion'=>'Abasolo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>2,'descripcion'=>'Acala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>3,'descripcion'=>'Acámbaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>4,'descripcion'=>'Acaponeta', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>5,'descripcion'=>'Acapulco de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>6,'descripcion'=>'Acatlán de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>7,'descripcion'=>'Acatlán de Osorio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>8,'descripcion'=>'Acayucan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>9,'descripcion'=>'Actopan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>10,'descripcion'=>'Agua Dulce', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>11,'descripcion'=>'Agua Prieta', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>12,'descripcion'=>'Aguascalientes', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>13,'descripcion'=>'Ahome', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>14,'descripcion'=>'Ahuacatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>15,'descripcion'=>'Ahualulco de Mercado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>16,'descripcion'=>'Ajijic', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>17,'descripcion'=>'Álamo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>18,'descripcion'=>'Allende', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>19,'descripcion'=>'Almoloya de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>20,'descripcion'=>'Altamira', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>21,'descripcion'=>'Altotonga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>22,'descripcion'=>'Alvarado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>23,'descripcion'=>'Amatepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>24,'descripcion'=>'Ameca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>25,'descripcion'=>'Amozoc', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>26,'descripcion'=>'Anáhuac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>27,'descripcion'=>'Ángel R. Cabada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>28,'descripcion'=>'Angostura', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>29,'descripcion'=>'Apan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>30,'descripcion'=>'Apaseo el Alto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>31,'descripcion'=>'Apaseo el Grande', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>32,'descripcion'=>'Apatzingán de la Constitución', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>33,'descripcion'=>'Apizaco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>34,'descripcion'=>'Arandas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>35,'descripcion'=>'Arcelia', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>36,'descripcion'=>'Arriaga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>37,'descripcion'=>'Arteaga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>38,'descripcion'=>'Asientos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>39,'descripcion'=>'Asunción Nochixtlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>40,'descripcion'=>'Atlixco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>41,'descripcion'=>'Atotonilco el Alto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>42,'descripcion'=>'Atoyac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>43,'descripcion'=>'Atoyac de Álvarez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>44,'descripcion'=>'Autlán de Navarro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>45,'descripcion'=>'Ayutla de los Libres', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>46,'descripcion'=>'Azoyú', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>47,'descripcion'=>'Bacalar', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>48,'descripcion'=>'Bachíniva', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>49,'descripcion'=>'Bahias de Huatulco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>50,'descripcion'=>'Banderilla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>51,'descripcion'=>'Bécal', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>52,'descripcion'=>'Boca del Río', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>53,'descripcion'=>'Bucerías', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>54,'descripcion'=>'Buenavista de Cuéllar', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>55,'descripcion'=>'Cabo San Lucas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>56,'descripcion'=>'Cacahoatán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>57,'descripcion'=>'Cadereyta Jiménez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>58,'descripcion'=>'Calkini', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>59,'descripcion'=>'Calpulalpan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>60,'descripcion'=>'Calvillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>61,'descripcion'=>'Canatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>62,'descripcion'=>'Cancún', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>63,'descripcion'=>'Candelaria', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>64,'descripcion'=>'Capulhuac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>65,'descripcion'=>'Cárdenas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>66,'descripcion'=>'Carlos A. Carrillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>67,'descripcion'=>'Castaños', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>68,'descripcion'=>'Catemaco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>69,'descripcion'=>'Cazones de Herrera', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>70,'descripcion'=>'Cedral', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>71,'descripcion'=>'Celaya', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>72,'descripcion'=>'Cerritos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>73,'descripcion'=>'Cerro Azul', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>74,'descripcion'=>'Chahuites', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>75,'descripcion'=>'Chalco de Díaz Covarrubias', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>76,'descripcion'=>'Champotón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>77,'descripcion'=>'Chapala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>78,'descripcion'=>'Charcas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>79,'descripcion'=>'Chetumal', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>80,'descripcion'=>'Chiapa de Corzo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>81,'descripcion'=>'Chiautempan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>82,'descripcion'=>'Chicoloapan de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>83,'descripcion'=>'Chiconcuac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>84,'descripcion'=>'Chihuahua', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>85,'descripcion'=>'Chilapa de Álvarez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>86,'descripcion'=>'Chilpancingo de los Bravo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>87,'descripcion'=>'Chimalhuacán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>88,'descripcion'=>'Choix', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>89,'descripcion'=>'Ciénega de Flores', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>90,'descripcion'=>'Cihuatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>91,'descripcion'=>'Cintalapa de Figueroa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>92,'descripcion'=>'Ciudad Acuña', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>93,'descripcion'=>'Ciudad Adolfo López Mateos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>94,'descripcion'=>'Ciudad Altamirano', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>95,'descripcion'=>'Ciudad Apaxtla de Castrejón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>96,'descripcion'=>'Ciudad Apodaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>97,'descripcion'=>'Ciudad Benito Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>98,'descripcion'=>'Ciudad Camargo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>99,'descripcion'=>'Ciudad Constitución', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>100,'descripcion'=>'Ciudad Cuauhtémoc', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>101,'descripcion'=>'Ciudad de Armería', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>102,'descripcion'=>'Ciudad de México', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>103,'descripcion'=>'Ciudad de Villa de Álvarez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>104,'descripcion'=>'Ciudad del Carmen', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>105,'descripcion'=>'Ciudad del Maíz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>106,'descripcion'=>'Ciudad General Escobedo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>107,'descripcion'=>'Ciudad Gustavo Díaz Ordaz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>108,'descripcion'=>'Ciudad Guzmán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>109,'descripcion'=>'Ciudad Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>110,'descripcion'=>'Ciudad Ixtepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>111,'descripcion'=>'Ciudad Lázaro Cárdenas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>112,'descripcion'=>'Ciudad Lerdo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>113,'descripcion'=>'Ciudad Madero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>114,'descripcion'=>'Ciudad Mante', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>115,'descripcion'=>'Ciudad Manuel Doblado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>116,'descripcion'=>'Ciudad Melchor Múzquiz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>117,'descripcion'=>'Ciudad Miguel Alemán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>118,'descripcion'=>'Ciudad Nezahualcóyotl', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>119,'descripcion'=>'Ciudad Nicolás Romero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>120,'descripcion'=>'Ciudad Obregón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>121,'descripcion'=>'Ciudad Río Bravo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>122,'descripcion'=>'Ciudad Sabinas Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>123,'descripcion'=>'Ciudad Santa Catarina', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>124,'descripcion'=>'Ciudad Serdán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>125,'descripcion'=>'Ciudad Tula', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>126,'descripcion'=>'Ciudad Valles', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>127,'descripcion'=>'Ciudad Victoria', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>128,'descripcion'=>'Coacalco de Berriozabal', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>129,'descripcion'=>'Coatepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>130,'descripcion'=>'Coatzacoalcos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>131,'descripcion'=>'Coatzintla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>132,'descripcion'=>'Cocula', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>133,'descripcion'=>'Colima', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>134,'descripcion'=>'Colonia Anáhuac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>135,'descripcion'=>'Colotlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>136,'descripcion'=>'Comalcalco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>137,'descripcion'=>'Comitán de Domínguez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>138,'descripcion'=>'Comonfort', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>139,'descripcion'=>'Compostela', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>140,'descripcion'=>'Copala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>141,'descripcion'=>'Córdoba', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>142,'descripcion'=>'Cortazar', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>143,'descripcion'=>'Cosalá', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>144,'descripcion'=>'Cosamaloapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>145,'descripcion'=>'Cosío', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>146,'descripcion'=>'Cosolapa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>147,'descripcion'=>'Cosoleacaque', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>148,'descripcion'=>'Cotija de la Paz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>149,'descripcion'=>'Coyuca de Benítez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>150,'descripcion'=>'Coyuca de Catalán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>151,'descripcion'=>'Cozumel', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>152,'descripcion'=>'Cruz Grande', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>153,'descripcion'=>'Cuajinicuilapa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>154,'descripcion'=>'Cuatro Ciénegas de Carranza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>155,'descripcion'=>'Cuauhtémoc', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>156,'descripcion'=>'Cuautitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>157,'descripcion'=>'Cuautitlán Izcalli', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>158,'descripcion'=>'Cuautla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>159,'descripcion'=>'Cuautlancingo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>160,'descripcion'=>'Cuerámaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>161,'descripcion'=>'Cuernavaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>162,'descripcion'=>'Cuichapa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>163,'descripcion'=>'Cuilápam de Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>164,'descripcion'=>'Cuitláhuac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>165,'descripcion'=>'Cuitzeo del Porvenir', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>166,'descripcion'=>'Culiacán Rosales', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>167,'descripcion'=>'Cunduacán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>168,'descripcion'=>'Cutzamala de Pinzón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>169,'descripcion'=>'Delicias', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>170,'descripcion'=>'Doctor Arroyo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>171,'descripcion'=>'Doctor Mora', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>172,'descripcion'=>'Dolores Hidalgo Cuna de la Independencia Nacional', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>173,'descripcion'=>'Ébano', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>174,'descripcion'=>'Ecatepec de Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>175,'descripcion'=>'El Camarón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>176,'descripcion'=>'El cercado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>177,'descripcion'=>'El Grullo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>178,'descripcion'=>'El Higo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>179,'descripcion'=>'El Naranjo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>180,'descripcion'=>'El Pueblito', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>181,'descripcion'=>'El Quince (San José el Quince)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>182,'descripcion'=>'El Rosario', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>183,'descripcion'=>'El Salto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>184,'descripcion'=>'Emiliano Zapata', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>185,'descripcion'=>'Empalme', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>186,'descripcion'=>'Empalme Escobedo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>187,'descripcion'=>'Ensenada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>188,'descripcion'=>'Escárcega', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>189,'descripcion'=>'Escuinapa de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>190,'descripcion'=>'Estación Manuel (Úrsulo Galván)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>191,'descripcion'=>'Estación Naranjo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>192,'descripcion'=>'Etzatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>193,'descripcion'=>'Felipe Carrillo Puerto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>194,'descripcion'=>'Fortín de las Flores', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>195,'descripcion'=>'Fracción el Refugio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>196,'descripcion'=>'Francisco I. Madero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>197,'descripcion'=>'Francisco I. Madero (Chávez)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>198,'descripcion'=>'Francisco I. Madero (Puga)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>199,'descripcion'=>'Fray Bernardino de Sahagún (Ciudad Sahagún)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>200,'descripcion'=>'Fresnillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>201,'descripcion'=>'Frontera', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>202,'descripcion'=>'Galeana', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>203,'descripcion'=>'García', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>204,'descripcion'=>'General Miguel Alemán (Potrero Nuevo)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>205,'descripcion'=>'Gómez Palacio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>206,'descripcion'=>'González', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>207,'descripcion'=>'Guadalajara', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>208,'descripcion'=>'Guadalupe', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>209,'descripcion'=>'Guamúchil', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>210,'descripcion'=>'Guanajuato', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>211,'descripcion'=>'Guasave', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>212,'descripcion'=>'Guerrero Negro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>213,'descripcion'=>'Gutiérrez Zamora', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>214,'descripcion'=>'Hecelchakán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>215,'descripcion'=>'Hermosillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>216,'descripcion'=>'Heroica Caborca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>217,'descripcion'=>'Heroica Ciudad de Cananea', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>218,'descripcion'=>'Heroica Ciudad de Ejutla de Crespo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>219,'descripcion'=>'Heroica Ciudad de Huajuapan de León', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>220,'descripcion'=>'Heroica Ciudad de Tlaxiaco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>221,'descripcion'=>'Heroica Guaymas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>222,'descripcion'=>'Heroica Matamoros', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>223,'descripcion'=>'Heroica Mulegé', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>224,'descripcion'=>'Heroica Nogales', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>225,'descripcion'=>'Heroica Puebla de Zaragoza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>226,'descripcion'=>'Heróica Zitácuaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>227,'descripcion'=>'Hidalgo del Parral', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>228,'descripcion'=>'Higuera de Zaragoza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>229,'descripcion'=>'Hopelchén', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>230,'descripcion'=>'Hualahuises', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>231,'descripcion'=>'Huamantla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>232,'descripcion'=>'Huamuxtitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>233,'descripcion'=>'Huanímaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>234,'descripcion'=>'Huatabampo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>235,'descripcion'=>'Huatusco de Chicuellar', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>236,'descripcion'=>'Huauchinango', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>237,'descripcion'=>'Huayacocotla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>238,'descripcion'=>'Huejuquilla el Alto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>239,'descripcion'=>'Huejutla de Reyes', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>240,'descripcion'=>'Huetamo de Núñez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>241,'descripcion'=>'Huiloapan de Cuauhtémoc', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>242,'descripcion'=>'Huimanguillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>243,'descripcion'=>'Huitzuco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>244,'descripcion'=>'Huixquilucan de Degollado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>245,'descripcion'=>'Huixtla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>246,'descripcion'=>'Iguala de la Independencia', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>247,'descripcion'=>'Irapuato', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>248,'descripcion'=>'Isla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>249,'descripcion'=>'Isla Mujeres', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>250,'descripcion'=>'Ixmiquilpan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>251,'descripcion'=>'Ixtaczoquitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>252,'descripcion'=>'Ixtapaluca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>253,'descripcion'=>'Ixtlán del Río', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>254,'descripcion'=>'Izúcar de Matamoros', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>255,'descripcion'=>'Jacona de Plancarte', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>256,'descripcion'=>'Jala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>257,'descripcion'=>'Jalostotitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>258,'descripcion'=>'Jalpa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>259,'descripcion'=>'Jalpa de Méndez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>260,'descripcion'=>'Jáltipan de Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>261,'descripcion'=>'Jamay', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>262,'descripcion'=>'Jaral del Progreso', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>263,'descripcion'=>'Jaumave', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>264,'descripcion'=>'Jerécuaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>265,'descripcion'=>'Jerez de García Salinas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>266,'descripcion'=>'Jesús María', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>267,'descripcion'=>'Jiquilpan de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>268,'descripcion'=>'Jiquipilas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>269,'descripcion'=>'Jiutepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>270,'descripcion'=>'Jocotepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>271,'descripcion'=>'Jojutla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>272,'descripcion'=>'José Cardel', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>273,'descripcion'=>'José Mariano Jiménez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>274,'descripcion'=>'Juan Aldama', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>275,'descripcion'=>'Juan Díaz Covarrubias', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>276,'descripcion'=>'Juan Rodríguez Clara', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>277,'descripcion'=>'Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>278,'descripcion'=>'Juchitán (Juchitán de Zaragoza)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>279,'descripcion'=>'Juchitepec de Mariano Rivapalacio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>280,'descripcion'=>'Kanasín', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>281,'descripcion'=>'Kantunilkín', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>282,'descripcion'=>'La Barca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>283,'descripcion'=>'La Cruz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>284,'descripcion'=>'La Paz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>285,'descripcion'=>'La Peñita de Jaltemba', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>286,'descripcion'=>'La Piedad de Cabadas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>287,'descripcion'=>'La Resolana', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>288,'descripcion'=>'La Unión', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>289,'descripcion'=>'Lagos de Moreno', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>290,'descripcion'=>'Lagunas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>291,'descripcion'=>'Las Choapas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>292,'descripcion'=>'Las Guacamayas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>293,'descripcion'=>'Las Margaritas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>294,'descripcion'=>'Las Pintitas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>295,'descripcion'=>'Las Rosas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>296,'descripcion'=>'Las Varas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>297,'descripcion'=>'León de los Aldama', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>298,'descripcion'=>'Lerdo de Tejada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>299,'descripcion'=>'Licenciado Benito Juárez (Campo Gobierno)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>300,'descripcion'=>'Linares', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>301,'descripcion'=>'Loma Bonita', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>302,'descripcion'=>'Loreto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>303,'descripcion'=>'Los Mochis', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>304,'descripcion'=>'Los Reyes Acaquilpan (La Paz)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>305,'descripcion'=>'Los Reyes de Salgado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>306,'descripcion'=>'Luis Moya', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>307,'descripcion'=>'Macuspana', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>308,'descripcion'=>'Madera', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>309,'descripcion'=>'Magdalena', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>310,'descripcion'=>'Magdalena de Kino', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>311,'descripcion'=>'Manuel Ojinaga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>312,'descripcion'=>'Manzanillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>313,'descripcion'=>'Mapastepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>314,'descripcion'=>'Maravatío de Ocampo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>315,'descripcion'=>'Marfil', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>316,'descripcion'=>'Mariscala de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>317,'descripcion'=>'Marquelia', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>318,'descripcion'=>'Martínez de la Torre', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>319,'descripcion'=>'Matamoros', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>320,'descripcion'=>'Matehuala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>321,'descripcion'=>'Matías Romero Avendaño', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>322,'descripcion'=>'Mazatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>323,'descripcion'=>'Melchor Ocampo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>324,'descripcion'=>'Mérida', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>325,'descripcion'=>'Metepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>326,'descripcion'=>'Mexicali', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>327,'descripcion'=>'Miahuatlán de Porfirio Díaz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>328,'descripcion'=>'Minatitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>329,'descripcion'=>'Mocorito', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>330,'descripcion'=>'Monclova', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>331,'descripcion'=>'Montemorelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>332,'descripcion'=>'Monterrey', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>333,'descripcion'=>'Morelia', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>334,'descripcion'=>'Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>335,'descripcion'=>'Moroleón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>336,'descripcion'=>'Motozintla de Mendoza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>337,'descripcion'=>'Motul de Carrillo Puerto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>338,'descripcion'=>'Moyahua de Estrada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>339,'descripcion'=>'Nadadores', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>340,'descripcion'=>'Naranjos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>341,'descripcion'=>'Natividad', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>342,'descripcion'=>'Naucalpan de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>343,'descripcion'=>'Nava', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>344,'descripcion'=>'Navojoa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>345,'descripcion'=>'Navolato', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>346,'descripcion'=>'Nochistlán de Mejía', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>347,'descripcion'=>'Nogales', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>348,'descripcion'=>'Nombre de Dios', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>349,'descripcion'=>'Nueva Ciudad Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>350,'descripcion'=>'Nueva Italia de Ruiz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>351,'descripcion'=>'Nueva Rosita', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>352,'descripcion'=>'Nuevo Casas Grandes', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>353,'descripcion'=>'Nuevo Laredo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>354,'descripcion'=>'Oaxaca de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>355,'descripcion'=>'Ocosingo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>356,'descripcion'=>'Ocotito', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>357,'descripcion'=>'Ocotlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>358,'descripcion'=>'Ocotlán de Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>359,'descripcion'=>'Ocoyoacac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>360,'descripcion'=>'Ocozocoautla de Espinosa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>361,'descripcion'=>'Ojocaliente', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>362,'descripcion'=>'Olinalá', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>363,'descripcion'=>'Orizaba', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>364,'descripcion'=>'Pabellón de Arteaga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>365,'descripcion'=>'Pachuca de Soto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>366,'descripcion'=>'Palenque', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>367,'descripcion'=>'Pánuco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>368,'descripcion'=>'Papantla de Olarte', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>369,'descripcion'=>'Paracho de Verduzco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>370,'descripcion'=>'Paraíso', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>371,'descripcion'=>'Paraje Nuevo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>372,'descripcion'=>'Parras de la Fuente', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>373,'descripcion'=>'Paso de Ovejas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>374,'descripcion'=>'Paso del Macho', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>375,'descripcion'=>'Pátzcuaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>376,'descripcion'=>'Pénjamo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>377,'descripcion'=>'Peñón Blanco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>378,'descripcion'=>'Perote', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>379,'descripcion'=>'Petatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>380,'descripcion'=>'Pichucalco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>381,'descripcion'=>'Piedras Negras', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>382,'descripcion'=>'Pijijiapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>383,'descripcion'=>'Platón Sánchez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>384,'descripcion'=>'Playa del Carmen', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>385,'descripcion'=>'Playa Vicente', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>386,'descripcion'=>'Playas de Rosarito', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>387,'descripcion'=>'Pomuch', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>388,'descripcion'=>'Poncitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>389,'descripcion'=>'Poza Rica de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>390,'descripcion'=>'Puente de Ixtla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>391,'descripcion'=>'Puerto Adolfo López Mateos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>392,'descripcion'=>'Puerto Escondido', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>393,'descripcion'=>'Puerto Madero (San Benito)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>394,'descripcion'=>'Puerto Peñasco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>395,'descripcion'=>'Puerto Vallarta', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>396,'descripcion'=>'Purísima de Bustos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>397,'descripcion'=>'Puruándiro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>398,'descripcion'=>'Putla Villa de Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>399,'descripcion'=>'Quilá', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>400,'descripcion'=>'Ramos Arizpe', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>401,'descripcion'=>'Reforma', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>402,'descripcion'=>'Reynosa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>403,'descripcion'=>'Rincón de Romos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>404,'descripcion'=>'Rincón de Tamayo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>405,'descripcion'=>'Río Blanco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>406,'descripcion'=>'Río Grande', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>407,'descripcion'=>'Río Grande o Piedra Parada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>408,'descripcion'=>'Rioverde', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>409,'descripcion'=>'Rodolfo Sánchez Taboada (Maneadero)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>410,'descripcion'=>'Romita', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>411,'descripcion'=>'Ruíz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>412,'descripcion'=>'Sabancuy', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>413,'descripcion'=>'Sabinas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>414,'descripcion'=>'Sahuayo de Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>415,'descripcion'=>'Salamanca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>416,'descripcion'=>'Salina Cruz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>417,'descripcion'=>'Salinas de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>418,'descripcion'=>'Saltillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>419,'descripcion'=>'Salvatierra', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>420,'descripcion'=>'San Andrés Cholula', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>421,'descripcion'=>'San Andrés Tuxtla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>422,'descripcion'=>'San Antonio de la Cal', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>423,'descripcion'=>'San Blas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>424,'descripcion'=>'San Blas Atempa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>425,'descripcion'=>'San Buenaventura', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>426,'descripcion'=>'San Cristóbal de las Casas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>427,'descripcion'=>'San Diego de Alejandría', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>428,'descripcion'=>'San Diego de la Unión', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>429,'descripcion'=>'San Felipe', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>430,'descripcion'=>'San Felipe Jalapa de Díaz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>431,'descripcion'=>'San Fernando', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>432,'descripcion'=>'San Francisco de Campeche', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>433,'descripcion'=>'San Francisco de los Romo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>434,'descripcion'=>'San Francisco del Rincón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>435,'descripcion'=>'San Francisco Ixhuatán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>436,'descripcion'=>'San Francisco Telixtlahuaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>437,'descripcion'=>'San Ignacio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>438,'descripcion'=>'San Ignacio Cerro Gordo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>439,'descripcion'=>'San Jerónimo de Juárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>440,'descripcion'=>'San José del Cabo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>441,'descripcion'=>'San José el Verde (El Verde)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>442,'descripcion'=>'San José Iturbide', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>443,'descripcion'=>'San Juan Bautista Cuicatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>444,'descripcion'=>'San Juan Bautista Lo de Soto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>445,'descripcion'=>'San Juan Bautista Tuxtepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>446,'descripcion'=>'San Juan Bautista Valle Nacional', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>447,'descripcion'=>'San Juan Cacahuatepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>448,'descripcion'=>'San Juan de los Lagos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>449,'descripcion'=>'San Juan del Rio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>450,'descripcion'=>'San Juan del Río del Centauro del Norte', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>451,'descripcion'=>'San Julián', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>452,'descripcion'=>'San Luis Acatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>453,'descripcion'=>'San Luis de la Loma', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>454,'descripcion'=>'San Luis de la Paz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>455,'descripcion'=>'San Luis Potosí', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>456,'descripcion'=>'San Luis Río Colorado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>457,'descripcion'=>'San Luis San Pedro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>458,'descripcion'=>'San Marcos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>459,'descripcion'=>'San Martín Texmelucan de Labastida', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>460,'descripcion'=>'San Mateo Atenco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>461,'descripcion'=>'San Miguel de Allende', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>462,'descripcion'=>'San Miguel el Alto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>463,'descripcion'=>'San Miguel el Grande', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>464,'descripcion'=>'San Miguel Vindho', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>465,'descripcion'=>'San Nicolás de los Garza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>466,'descripcion'=>'San Pablo Huitzo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>467,'descripcion'=>'San Pablo Villa de Mitla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>468,'descripcion'=>'San Pedro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>469,'descripcion'=>'San Pedro Cholula', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>470,'descripcion'=>'San Pedro Garza García', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>471,'descripcion'=>'San Pedro Lagunillas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>472,'descripcion'=>'San Pedro Mixtepec Distrito 22', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>473,'descripcion'=>'San Pedro Pochutla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>474,'descripcion'=>'San Pedro Tapanatepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>475,'descripcion'=>'San Pedro Totolápam', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>476,'descripcion'=>'San Rafael', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>477,'descripcion'=>'San Sebastián Tecomaxtlahuaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>478,'descripcion'=>'Santa Cruz Itundujia', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>479,'descripcion'=>'Santa Cruz Juventino Rosas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>480,'descripcion'=>'Santa Lucía del Camino', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>481,'descripcion'=>'Santa María del Oro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>482,'descripcion'=>'Santa María del Río', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>483,'descripcion'=>'Santa María Huatulco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>484,'descripcion'=>'Santa Maria Tultepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>485,'descripcion'=>'Santa Rosa Treinta', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>486,'descripcion'=>'Santa Rosalía', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>487,'descripcion'=>'Santa Rosalía de Camargo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>488,'descripcion'=>'Santiago', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>489,'descripcion'=>'Santiago de Querétaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>490,'descripcion'=>'Santiago Ixcuintla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>491,'descripcion'=>'Santiago Jamiltepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>492,'descripcion'=>'Santiago Juxtlahuaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>493,'descripcion'=>'Santiago Maravatío', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>494,'descripcion'=>'Santiago Papasquiaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>495,'descripcion'=>'Santiago Pinotepa Nacional', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>496,'descripcion'=>'Santiago Suchilquitongo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>497,'descripcion'=>'Santiago Tulantepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>498,'descripcion'=>'Santiago Tuxtla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>499,'descripcion'=>'Santo Domingo Tehuantepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>500,'descripcion'=>'Saucillo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>501,'descripcion'=>'Sayula', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>502,'descripcion'=>'Sihuapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>503,'descripcion'=>'Silao', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>504,'descripcion'=>'Sinaloa de Leyva', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>505,'descripcion'=>'Soledad de Doblado', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>506,'descripcion'=>'Soledad de Graciano Sánchez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>507,'descripcion'=>'Sombrerete', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>508,'descripcion'=>'Sonoyta', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>509,'descripcion'=>'Soto la Marina', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>510,'descripcion'=>'Tacámbaro de Codallos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>511,'descripcion'=>'Tala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>512,'descripcion'=>'Talpa de Allende', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>513,'descripcion'=>'Tamasopo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>514,'descripcion'=>'Tamazula de Gordiano', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>515,'descripcion'=>'Tamazunchale', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>516,'descripcion'=>'Tampico', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>517,'descripcion'=>'Tampico Alto', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>518,'descripcion'=>'Tamuín', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>519,'descripcion'=>'Tangancícuaro de Arista', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>520,'descripcion'=>'Tantoyuca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>521,'descripcion'=>'Tapachula de Córdova y Ordóñez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>522,'descripcion'=>'Tarandacuao', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>523,'descripcion'=>'Taxco de Alarcón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>524,'descripcion'=>'Teapa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>525,'descripcion'=>'Tecalitlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>526,'descripcion'=>'Tecámac de Felipe Villanueva', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>527,'descripcion'=>'Tecamachalco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>528,'descripcion'=>'Tecate', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>529,'descripcion'=>'Tecomán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>530,'descripcion'=>'Técpan de Galeana', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>531,'descripcion'=>'Tecuala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>532,'descripcion'=>'Tehuacán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>533,'descripcion'=>'Tejupilco de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>534,'descripcion'=>'Teloloapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>535,'descripcion'=>'Temixco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>536,'descripcion'=>'Tempoal de Sánchez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>537,'descripcion'=>'Tenabo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>538,'descripcion'=>'Tenosique de Pino Suárez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>539,'descripcion'=>'Teocaltiche', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>540,'descripcion'=>'Teotitlán de Flores Magón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>541,'descripcion'=>'Tepatitlán de Morelos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>542,'descripcion'=>'Tepeaca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>543,'descripcion'=>'Tepeapulco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>544,'descripcion'=>'Tepeji del Río de Ocampo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>545,'descripcion'=>'Tepezalá', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>546,'descripcion'=>'Tepic', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>547,'descripcion'=>'Tepotzotlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>548,'descripcion'=>'Tequila', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>549,'descripcion'=>'Tequixquiac', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>550,'descripcion'=>'Texcoco de Mora', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>551,'descripcion'=>'Teziutlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>552,'descripcion'=>'Tezonapa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>553,'descripcion'=>'Ticul', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>554,'descripcion'=>'Tierra Blanca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>555,'descripcion'=>'Tierra Colorada', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>556,'descripcion'=>'Tierra Nueva', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>557,'descripcion'=>'Tihuatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>558,'descripcion'=>'Tijuana', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>559,'descripcion'=>'Tixtla de Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>560,'descripcion'=>'Tizayuca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>561,'descripcion'=>'Tizimín', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>562,'descripcion'=>'Tlacojalpan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>563,'descripcion'=>'Tlacolula de Matamoros', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>564,'descripcion'=>'Tlajomulco de Zúñiga', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>565,'descripcion'=>'Tlalnepantla de Baz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>566,'descripcion'=>'Tlapa de Comonfort', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>567,'descripcion'=>'Tlapacoyan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>568,'descripcion'=>'Tlapehuala', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>569,'descripcion'=>'Tlaquepaque', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>570,'descripcion'=>'Tlaquiltenango', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>571,'descripcion'=>'Tlaxcala de Xicohténcatl', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>572,'descripcion'=>'Tlaxcoapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>573,'descripcion'=>'Todos Santos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>574,'descripcion'=>'Toluca de Lerdo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>575,'descripcion'=>'Tonalá', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>576,'descripcion'=>'Topolobampo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>577,'descripcion'=>'Torreón', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>578,'descripcion'=>'Tototlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>579,'descripcion'=>'Tres Valles', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>580,'descripcion'=>'Tula de Allende', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>581,'descripcion'=>'Tulancingo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>582,'descripcion'=>'Tultitlán de Mariano Escobedo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>583,'descripcion'=>'Túxpam de Rodríguez Cano', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>584,'descripcion'=>'Tuxpan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>585,'descripcion'=>'Tuxtla Gutiérrez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>586,'descripcion'=>'Unión de San Antonio', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>587,'descripcion'=>'Unión Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>588,'descripcion'=>'Uriangato', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>589,'descripcion'=>'Uruapan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>590,'descripcion'=>'Valladolid', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>591,'descripcion'=>'Valle de Chalco Solidaridad', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>592,'descripcion'=>'Valle de Guadalupe', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>593,'descripcion'=>'Valle de Santiago', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>594,'descripcion'=>'Valle Hermoso', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>595,'descripcion'=>'Valparaíso', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>596,'descripcion'=>'Venustiano Carranza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>597,'descripcion'=>'Veracruz', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>598,'descripcion'=>'Vicente Camalote', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>599,'descripcion'=>'Vicente Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>600,'descripcion'=>'Víctor Rosales', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>601,'descripcion'=>'Victoria de Durango', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>602,'descripcion'=>'Viesca', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>603,'descripcion'=>'Villa Alberto Andrés Alvarado Arámburo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>604,'descripcion'=>'Villa Corona', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>605,'descripcion'=>'Villa de Cos', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>606,'descripcion'=>'Villa de Reyes', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>607,'descripcion'=>'Villa de Tamazulápam del Progreso', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>608,'descripcion'=>'Villa de Zaachila', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>609,'descripcion'=>'Villa Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>610,'descripcion'=>'Villa Hidalgo (El Nuevo)', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>611,'descripcion'=>'Villa Purificación', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>612,'descripcion'=>'Villa Sola de Vega', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>613,'descripcion'=>'Villa Unión', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>614,'descripcion'=>'Villa Vicente Guerrero', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>615,'descripcion'=>'Villaflores', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>616,'descripcion'=>'Villagrán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>617,'descripcion'=>'Villahermosa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>618,'descripcion'=>'Villanueva', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>619,'descripcion'=>'Xalapa-Enríquez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>620,'descripcion'=>'Xalisco', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>621,'descripcion'=>'Xicoténcatl', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>622,'descripcion'=>'Xicotepec', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>623,'descripcion'=>'Xonacatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>624,'descripcion'=>'Yahualica de González Gallo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>625,'descripcion'=>'Yautepec de Zaragoza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>626,'descripcion'=>'Yecuatla', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>627,'descripcion'=>'Yurécuaro', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>628,'descripcion'=>'Yuriria', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>629,'descripcion'=>'Zacapu', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>630,'descripcion'=>'Zacatecas', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>631,'descripcion'=>'Zacatepec de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>632,'descripcion'=>'Zacatlán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>633,'descripcion'=>'Zacoalco de Torres', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>634,'descripcion'=>'Zamora de Hidalgo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>635,'descripcion'=>'Zapopan', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>636,'descripcion'=>'Zapotiltic', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>637,'descripcion'=>'Zaragoza', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>638,'descripcion'=>'Zihuatanejo', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>639,'descripcion'=>'Zimapán', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>640,'descripcion'=>'Zimatlán de Álvarez', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>641,'descripcion'=>'Zinapécuaro de Figueroa', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>642,'descripcion'=>'Zumpango', 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>643,'descripcion'=>'Zumpango del Río', 'created_at'=>now(), 'updated_at'=>now()],

        ]);
    }
}
